site_name: TradeFinex
site_description: Peer to Peer decentralized Trade and Finance using Blockchain Technology
theme:
  name: 'readthedocs'
  custom_dir: material_override
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: True
  - codehilite:
      guess_lang: false

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
    - css/style.css

extra:
    disqus:
    social:
        - type: 'github'
          link: 'https://github.com/XinFinOrg/Docs-TF'
        - type: 'twitter'
          link: 'https://twitter.com/xinfinf'
        - type: 'reddit'
          link: 'https://www.reddit.com/r/xinfin/'
        - type: 'facebook'
          link: 'https://www.facebook.com/pages/xinfin'
        - type: 'telegram'
          link: 'https://t.me/xinfintalk'
        - type: 'medium'
          link: 'https://medium.com/xinfin'

site_url: https://www.tradefinex.org
repo_url: https://github.com/XinFinOrg/Docs-TF
repo_name: XinFinOrg/Docs-TF

nav:
    - Introduction: index.md
    - Getting Started:
        - Guide/how_to_setup.md
        - Guide/API.md
    - Media Room:
        - Media/Articles.md
    - FAQ:
        - faq/General.md
        - faq/Advantage.md
        - faq/Participants.md
        - faq/ProjectFinancing.md
        - faq/Contracting.md
copyright: If you wish to improve this site, please <a href="https://github.com/XinFinOrg/Docs-TF/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/XinFinOrg/Docs-TF/issues/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>TradeFinex.
